### ISSUE TITLE
Execute multiple rpcs in a test case for testing different param values

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#25]
## Example

```
- testcase:
      name: if_ethernet_duplex_mode
      id: 2
      description: >
          This test is to define the duplex mode in an interface.
      rpcs:
          - template: if_ethernet_duplex_mode.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   name: "GigabitEthernet0/0/0/4"
                   duplex_mode: "FULL"
      rpcs:
          - template: if_ethernet_duplex_mode.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   name: "GigabitEthernet0/0/0/4"
                   duplex_mode: "HALF"

```
